spring:
    pulsar:
      client:
#        service-url: pulsar+ssl://sn-academy.sndevadvocate.snio.cloud:6651
#        auth-plugin-class-name: org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
#        authentication:
#          issuer-url: https://auth.streamnative.cloud/
#          private-key: file:///Users/tspann/Downloads/sndevadvocate-tspann.json
#          audience: urn:sn:pulsar:sndevadvocate:my-instance
#        service-url: pulsar://72.82.137.252:6650
        service-url: pulsar://pulsar1:6650
      producer:
        batching-enabled: false
        send-timeout-ms: 90000
        producer-name: bertqaspringboot
        topic-name: persistent://public/default/rawtext2
logging:
  level:
    org.apache.pulsar: error
    root: info
    ROOT: info
    dev.datainmotion.bertqa: info
server.port: 8789